# 定义自动化工作流
name: Deploy to Server
on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'
      - name: Install dependencies
        run: npm install
      - name: Run tests
        run: npm test

      - name: Build the project
        run: npm run build

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with: 
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
        
         
      - name: Deploy to Server
        run: |
          mkdir -p ~/.ssh
           # 将目标服务器的主机密钥添加到 known_hosts，避免第一次连接时需要手动验证
          ssh-keyscan -H 121.4.254.104 >> ~/.ssh/known_hosts
          chmod 700 ~/.ssh
          chmod 644 ~/.ssh/known_hosts
          scp -r ./build/* ubuntu@121.4.254.104:/var/www/frontend
          